version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: zwmon_mongodb
    restart: always
    volumes:
      - /var/lib/mongo:/data/db
    ports:
      - "127.0.0.1:27017:27017" # Only expose to localhost for safety

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: zwmon_backend
    restart: always
    env_file: .env
    environment:
      - MONGO_URL=mongodb://zwmon_user:PasswordAndalan2026@mongodb:27017/zwmon_db
      - DB_NAME=zwmon_db
      - TZ=Asia/Makassar
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/venv # Prevent overriding container venv


