version: '3.8'

services:
  mongodb:
    image: mongo:4.4
    container_name: zwmon_mongodb
    restart: always
    volumes:
      - /var/lib/mongo:/data/db
    ports:
      - "127.0.0.1:27017:27017"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: zwmon_backend
    restart: always
    env_file: .env
    environment:
      - MONGO_URL=mongodb://zwmon_user:PasswordAndalan2026@mongodb:27017/zwmon_db
      - DB_NAME=zwmon_db
      - TZ=Asia/Makassar
      - MEDIAMTX_API_URL=http://mediamtx:9997
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    volumes:
      - ./backend:/app
      - /app/venv

  mediamtx:
    image: bluenviron/mediamtx:latest
    container_name: zwmon_mediamtx
    restart: always
    ports:
      - "9997:9997"
      - "127.0.0.1:8889:8889"
      - "8189:8189/udp"
    environment:
      - MTX_WEBRTCADDITIONALHOSTS=103.151.20.98
      - MTX_API=yes
      - MTX_APIADDRESS=:9997
      - MTX_WEBRTCADDRESS=0.0.0.0:8889
    volumes:
      - ./mediamtx.yml:/mediamtx.yml
